require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MediafilesController do

  # This should return the minimal set of attributes required to create a valid
  # Mediafile. As you add validations to Mediafile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mediafiles as @mediafiles" do
      mediafile = Mediafile.create! valid_attributes
      get :index
      assigns(:mediafiles).should eq([mediafile])
    end
  end

  describe "GET show" do
    it "assigns the requested mediafile as @mediafile" do
      mediafile = Mediafile.create! valid_attributes
      get :show, :id => mediafile.id.to_s
      assigns(:mediafile).should eq(mediafile)
    end
  end

  describe "GET new" do
    it "assigns a new mediafile as @mediafile" do
      get :new
      assigns(:mediafile).should be_a_new(Mediafile)
    end
  end

  describe "GET edit" do
    it "assigns the requested mediafile as @mediafile" do
      mediafile = Mediafile.create! valid_attributes
      get :edit, :id => mediafile.id.to_s
      assigns(:mediafile).should eq(mediafile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mediafile" do
        expect {
          post :create, :mediafile => valid_attributes
        }.to change(Mediafile, :count).by(1)
      end

      it "assigns a newly created mediafile as @mediafile" do
        post :create, :mediafile => valid_attributes
        assigns(:mediafile).should be_a(Mediafile)
        assigns(:mediafile).should be_persisted
      end

      it "redirects to the created mediafile" do
        post :create, :mediafile => valid_attributes
        response.should redirect_to(Mediafile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mediafile as @mediafile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mediafile.any_instance.stub(:save).and_return(false)
        post :create, :mediafile => {}
        assigns(:mediafile).should be_a_new(Mediafile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mediafile.any_instance.stub(:save).and_return(false)
        post :create, :mediafile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mediafile" do
        mediafile = Mediafile.create! valid_attributes
        # Assuming there are no other mediafiles in the database, this
        # specifies that the Mediafile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mediafile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mediafile.id, :mediafile => {'these' => 'params'}
      end

      it "assigns the requested mediafile as @mediafile" do
        mediafile = Mediafile.create! valid_attributes
        put :update, :id => mediafile.id, :mediafile => valid_attributes
        assigns(:mediafile).should eq(mediafile)
      end

      it "redirects to the mediafile" do
        mediafile = Mediafile.create! valid_attributes
        put :update, :id => mediafile.id, :mediafile => valid_attributes
        response.should redirect_to(mediafile)
      end
    end

    describe "with invalid params" do
      it "assigns the mediafile as @mediafile" do
        mediafile = Mediafile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mediafile.any_instance.stub(:save).and_return(false)
        put :update, :id => mediafile.id.to_s, :mediafile => {}
        assigns(:mediafile).should eq(mediafile)
      end

      it "re-renders the 'edit' template" do
        mediafile = Mediafile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mediafile.any_instance.stub(:save).and_return(false)
        put :update, :id => mediafile.id.to_s, :mediafile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mediafile" do
      mediafile = Mediafile.create! valid_attributes
      expect {
        delete :destroy, :id => mediafile.id.to_s
      }.to change(Mediafile, :count).by(-1)
    end

    it "redirects to the mediafiles list" do
      mediafile = Mediafile.create! valid_attributes
      delete :destroy, :id => mediafile.id.to_s
      response.should redirect_to(mediafiles_url)
    end
  end

end
